package terraform

import (
	"encoding/json"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/realmlint/realmlint/pkg/realm"
)

// builtInClients are created by Keycloak in every realm; they are not
// exported.
var builtInClients = map[string]bool{
	"account": true, "account-console": true, "admin-cli": true, "broker": true,
	"realm-management": true, "security-admin-console": true,
}

// Export writes Terraform configuration for the keycloak/keycloak provider
// that reproduces the realms' main settings, with import blocks so a first
// terraform plan adopts the existing objects instead of creating them.
// Secrets are never written: they become variables.
func Export(w io.Writer, realms []*realm.Realm) error {
	e := &exporter{names: map[string]int{}}
	e.line(`# Generated by realmlint from a Keycloak realm export.`)
	e.line(`# Review before applying. Users, client scopes, flows and role`)
	e.line(`# mappings are not exported. Run terraform plan first: it should show`)
	e.line(`# imports and few changes.`)
	e.line(``)
	e.line(`terraform {`)
	e.line(`  required_version = ">= 1.5"`)
	e.line(`  required_providers {`)
	e.line(`    keycloak = {`)
	e.line(`      source  = "keycloak/keycloak"`)
	e.line(`      version = ">= 5.0"`)
	e.line(`    }`)
	e.line(`  }`)
	e.line(`}`)
	for _, r := range realms {
		e.realm(r)
	}
	for _, v := range e.variables {
		e.line(``)
		e.line(`variable %s {`, quote(v))
		e.line(`  type      = string`)
		e.line(`  sensitive = true`)
		e.line(`}`)
	}
	_, err := io.WriteString(w, align(e.b.String()))
	return err
}

var attrLine = regexp.MustCompile(`^(\s*)([a-z_][a-z0-9_]*)\s*=\s(.*)$`)

// align lines up the = of consecutive attributes at the same indentation,
// the way terraform fmt does.
func align(text string) string {
	lines := strings.Split(text, "\n")
	for i := 0; i < len(lines); {
		m := attrLine.FindStringSubmatch(lines[i])
		if m == nil {
			i++
			continue
		}
		j, width := i, 0
		for j < len(lines) {
			n := attrLine.FindStringSubmatch(lines[j])
			if n == nil || n[1] != m[1] {
				break
			}
			width = max(width, len(n[2]))
			j++
		}
		for k := i; k < j; k++ {
			n := attrLine.FindStringSubmatch(lines[k])
			lines[k] = n[1] + n[2] + strings.Repeat(" ", width-len(n[2])) + " = " + n[3]
		}
		i = j
	}
	return strings.Join(lines, "\n")
}

type exporter struct {
	b         strings.Builder
	names     map[string]int
	variables []string
}

func (e *exporter) line(format string, args ...any) {
	if len(args) == 0 {
		e.b.WriteString(format)
	} else {
		fmt.Fprintf(&e.b, format, args...)
	}
	e.b.WriteString("\n")
}

var nonIdent = regexp.MustCompile(`[^a-z0-9_]+`)

// ident makes a unique Terraform resource name.
func (e *exporter) ident(kind, name string) string {
	id := strings.Trim(nonIdent.ReplaceAllString(strings.ToLower(name), "_"), "_")
	if id == "" || (id[0] >= '0' && id[0] <= '9') {
		id = "r_" + id
	}
	key := kind + "." + id
	e.names[key]++
	if n := e.names[key]; n > 1 {
		id = fmt.Sprintf("%s_%d", id, n)
	}
	return id
}

func (e *exporter) imports(to, id string) {
	if id == "" {
		return
	}
	e.line(``)
	e.line(`import {`)
	e.line(`  to = %s`, to)
	e.line(`  id = %s`, quote(id))
	e.line(`}`)
}

func (e *exporter) realm(r *realm.Realm) {
	rn := e.ident("realm", r.Realm)
	ref := "keycloak_realm." + rn + ".id"
	e.line(``)
	e.line(`# ---- realm %s ----`, r.Realm)
	e.imports("keycloak_realm."+rn, r.Realm)
	e.line(``)
	e.line(`resource "keycloak_realm" %s {`, quote(rn))
	e.attr("realm", r.Realm)
	e.attr("enabled", r.Enabled)
	if dn, ok := r.Raw["displayName"].(string); ok && dn != "" {
		e.attr("display_name", dn)
	}
	if alg, ok := r.Raw["defaultSignatureAlgorithm"].(string); ok && alg != "" {
		e.attr("default_signature_algorithm", alg)
	}
	if r.SSLRequired != "" {
		e.attr("ssl_required", r.SSLRequired)
	}
	e.attr("registration_allowed", r.RegistrationAllowed)
	e.attr("verify_email", r.VerifyEmail)
	if r.PasswordPolicy != "" {
		e.attr("password_policy", r.PasswordPolicy)
	}
	e.duration("access_token_lifespan", r.AccessTokenLifespan)
	e.duration("sso_session_idle_timeout", r.SSOSessionIdleTimeout)
	e.duration("sso_session_max_lifespan", r.SSOSessionMaxLifespan)
	if r.OfflineSessionMaxLifespanEnabled {
		e.attr("offline_session_max_lifespan_enabled", true)
		e.duration("offline_session_max_lifespan", r.OfflineSessionMaxLifespan)
	}
	if r.BruteForceProtected {
		e.line(``)
		e.line(`  security_defenses {`)
		e.line(`    brute_force_detection {`)
		e.line(`      permanent_lockout  = %t`, r.PermanentLockout)
		if r.FailureFactor > 0 {
			e.line(`      max_login_failures = %d`, r.FailureFactor)
		}
		for _, f := range [][2]string{
			{"waitIncrementSeconds", "wait_increment_seconds"},
			{"quickLoginCheckMilliSeconds", "quick_login_check_milli_seconds"},
			{"minimumQuickLoginWaitSeconds", "minimum_quick_login_wait_seconds"},
			{"maxFailureWaitSeconds", "max_failure_wait_seconds"},
			{"maxDeltaTimeSeconds", "failure_reset_time_seconds"},
		} {
			if n, ok := number(r.Raw[f[0]]); ok {
				e.line(`      %s = %d`, f[1], n)
			}
		}
		e.line(`    }`)
		e.line(`  }`)
	}
	e.line(`}`)

	e.line(``)
	e.line(`resource "keycloak_realm_events" %s {`, quote(rn))
	e.line(`  realm_id                     = %s`, ref)
	e.line(`  events_enabled               = %t`, r.EventsEnabled)
	e.line(`  admin_events_enabled         = %t`, r.AdminEventsEnabled)
	e.line(`  admin_events_details_enabled = %t`, r.AdminEventsDetailsEnabled)
	e.line(`}`)

	for i := range r.Clients {
		e.client(r, &r.Clients[i], ref)
	}
	roles := append([]realm.Role(nil), r.Roles.Realm...)
	sort.Slice(roles, func(i, j int) bool { return roles[i].Name < roles[j].Name })
	for _, role := range roles {
		if role.Name == "offline_access" || role.Name == "uma_authorization" || role.Name == "default-roles-"+r.Realm {
			continue
		}
		id := e.ident("role", role.Name)
		e.imports("keycloak_role."+id, idOf(r.Realm, role.ID))
		e.line(``)
		e.line(`resource "keycloak_role" %s {`, quote(id))
		e.line(`  realm_id = %s`, ref)
		e.attr("name", role.Name)
		if role.Description != "" {
			e.attr("description", role.Description)
		}
		e.line(`}`)
	}
	e.groups(r, r.Groups, ref, "")
	for i := range r.IdentityProviders {
		e.idp(r, &r.IdentityProviders[i], ref)
	}
}

func idOf(realmName, id string) string {
	if id == "" {
		return ""
	}
	return realmName + "/" + id
}

func (e *exporter) client(r *realm.Realm, c *realm.Client, ref string) {
	if builtInClients[c.ClientID] || strings.HasSuffix(c.ClientID, "-realm") {
		return
	}
	if c.Protocol != "" && c.Protocol != "openid-connect" {
		e.line(``)
		e.line(`# Client %s uses %s and is not exported.`, quote(c.ClientID), c.Protocol)
		return
	}
	id := e.ident("client", c.ClientID)
	addr := "keycloak_openid_client." + id
	e.imports(addr, idOf(r.Realm, c.ID))
	e.line(``)
	e.line(`resource "keycloak_openid_client" %s {`, quote(id))
	e.line(`  realm_id = %s`, ref)
	e.attr("client_id", c.ClientID)
	if c.Name != "" {
		e.attr("name", c.Name)
	}
	e.attr("enabled", c.IsEnabled())
	access := "CONFIDENTIAL"
	switch {
	case c.BearerOnly:
		access = "BEARER-ONLY"
	case c.PublicClient:
		access = "PUBLIC"
	}
	e.attr("access_type", access)
	if !c.BearerOnly {
		e.attr("standard_flow_enabled", c.UsesStandardFlow())
		e.attr("implicit_flow_enabled", c.ImplicitFlowEnabled)
		e.attr("direct_access_grants_enabled", c.DirectAccessGrantsEnabled)
		e.attr("service_accounts_enabled", c.ServiceAccountsEnabled)
	}
	if c.RootURL != "" {
		e.attr("root_url", c.RootURL)
	}
	if c.BaseURL != "" {
		e.attr("base_url", c.BaseURL)
	}
	if len(c.RedirectURIs) > 0 {
		e.attr("valid_redirect_uris", c.RedirectURIs)
	}
	if len(c.WebOrigins) > 0 {
		e.attr("web_origins", c.WebOrigins)
	}
	if m := c.Attributes["pkce.code.challenge.method"]; m != "" {
		e.attr("pkce_code_challenge_method", m)
	}
	if c.FullScopeAllowed != nil {
		e.attr("full_scope_allowed", *c.FullScopeAllowed)
	}
	// The provider's defaults for these differ from Keycloak's stored
	// values, so write what the realm has.
	if !c.BearerOnly {
		e.attr("use_refresh_tokens", c.Attributes["use.refresh.tokens"] == "true")
	}
	e.attr("backchannel_logout_session_required", c.Attributes["backchannel.logout.session.required"] == "true")
	e.line(`}`)
}

func (e *exporter) groups(r *realm.Realm, groups []realm.Group, ref, parent string) {
	for i := range groups {
		g := &groups[i]
		id := e.ident("group", g.Name)
		addr := "keycloak_group." + id
		e.imports(addr, idOf(r.Realm, g.ID))
		e.line(``)
		e.line(`resource "keycloak_group" %s {`, quote(id))
		e.line(`  realm_id  = %s`, ref)
		if parent != "" {
			e.line(`  parent_id = %s.id`, parent)
		}
		e.attr("name", g.Name)
		e.line(`}`)
		e.groups(r, g.SubGroups, ref, addr)
	}
}

func (e *exporter) idp(r *realm.Realm, p *realm.IdentityProvider, ref string) {
	cfg := func(k string) string { return p.Config[k] }
	switch p.ProviderID {
	case "oidc", "keycloak-oidc":
		id := e.ident("idp", p.Alias)
		secret := "idp_" + id + "_client_secret"
		e.variables = append(e.variables, secret)
		e.imports("keycloak_oidc_identity_provider."+id, idOf(r.Realm, p.Alias))
		e.line(``)
		e.line(`resource "keycloak_oidc_identity_provider" %s {`, quote(id))
		e.line(`  realm             = %s`, ref)
		e.attr("alias", p.Alias)
		e.attr("enabled", p.Enabled)
		if p.DisplayName != "" {
			e.attr("display_name", p.DisplayName)
		}
		e.attr("authorization_url", cfg("authorizationUrl"))
		e.attr("token_url", cfg("tokenUrl"))
		e.attr("client_id", cfg("clientId"))
		e.line(`  client_secret     = var.%s`, secret)
		if v := cfg("validateSignature"); v != "" {
			e.attr("validate_signature", v == "true")
		}
		e.idpCommon(r, p)
		e.line(`}`)
	case "saml":
		id := e.ident("idp", p.Alias)
		e.imports("keycloak_saml_identity_provider."+id, idOf(r.Realm, p.Alias))
		e.line(``)
		e.line(`resource "keycloak_saml_identity_provider" %s {`, quote(id))
		e.line(`  realm             = %s`, ref)
		e.attr("alias", p.Alias)
		e.attr("enabled", p.Enabled)
		if p.DisplayName != "" {
			e.attr("display_name", p.DisplayName)
		}
		e.attr("entity_id", cfg("entityId"))
		e.attr("single_sign_on_service_url", cfg("singleSignOnServiceUrl"))
		e.attr("validate_signature", cfg("validateSignature") == "true")
		if c := cfg("signingCertificate"); c != "" {
			e.attr("signing_certificate", c)
		}
		e.idpCommon(r, p)
		e.line(`}`)
	default:
		e.line(``)
		e.line(`# Identity provider %s (%s) is not exported.`, quote(p.Alias), p.ProviderID)
	}
}

// idpCommon writes identity provider settings whose provider defaults
// differ from Keycloak's.
func (e *exporter) idpCommon(r *realm.Realm, p *realm.IdentityProvider) {
	raw := rawProvider(r, p.Alias)
	if v, ok := raw["storeToken"].(bool); ok {
		e.attr("store_token", v)
	}
	if v, ok := raw["firstBrokerLoginFlowAlias"].(string); ok && v != "" {
		e.attr("first_broker_login_flow_alias", v)
	}
	if v := p.Config["syncMode"]; v != "" {
		e.attr("sync_mode", v)
	}
}

func rawProvider(r *realm.Realm, alias string) map[string]any {
	list, _ := r.Raw["identityProviders"].([]any)
	for _, x := range list {
		if m, ok := x.(map[string]any); ok && m["alias"] == alias {
			return m
		}
	}
	return nil
}

// number reads a JSON number from a raw export.
func number(v any) (int64, bool) {
	switch x := v.(type) {
	case json.Number:
		n, err := x.Int64()
		return n, err == nil
	case float64:
		return int64(x), true
	}
	return 0, false
}

// attr writes one attribute, aligned the way terraform fmt does not mind.
func (e *exporter) attr(name string, v any) {
	var val string
	switch x := v.(type) {
	case string:
		val = quote(x)
	case bool:
		val = fmt.Sprintf("%t", x)
	case []string:
		parts := make([]string, len(x))
		for i, s := range x {
			parts[i] = quote(s)
		}
		val = "[" + strings.Join(parts, ", ") + "]"
	default:
		val = fmt.Sprint(x)
	}
	e.line(`  %s = %s`, name, val)
}

// duration writes a lifetime in seconds as a provider duration ("5m0s").
func (e *exporter) duration(name string, seconds int) {
	if seconds > 0 {
		e.attr(name, (time.Duration(seconds) * time.Second).String())
	}
}

// quote writes an HCL string, escaping interpolation sequences so values
// are taken literally.
func quote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`, "${", "$${", "%{", "%%{")
	return `"` + r.Replace(s) + `"`
}
