package check

import (
	"fmt"
	"strings"
)

// CatalogMarkdown returns the check catalog as Markdown, for docs/checks.md.
// Regenerate the file with `go run ./tools/gendocs` after changing checks.
func CatalogMarkdown() string {
	var b strings.Builder
	b.WriteString("# Check catalog\n\n")
	b.WriteString("<!-- Generated by `go run ./tools/gendocs`. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "realmlint runs %d checks. Each finding has a severity (low, medium, high or critical) "+
		"that depends on what was found, so one check can report different severities.\n\n", len(All()))
	b.WriteString("To ignore a check, add it to `.realmlint.yaml` with a reason. See the README.\n")

	for _, g := range Groups() {
		fmt.Fprintf(&b, "\n## %s\n\n", g.Name)
		for _, c := range g.Checks {
			fmt.Fprintf(&b, "- [`%s`](#%s): %s\n", c.ID, c.ID, c.Title)
		}
	}
	for _, g := range Groups() {
		for _, c := range g.Checks {
			fmt.Fprintf(&b, "\n### %s\n\n**%s**\n\n%s\n\n**Fix:** %s\n", c.ID, c.Title, c.Why, c.Fix)
		}
	}
	return b.String()
}
